//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scholar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class papers
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> cit { get; set; }
        public string url { get; set; }
        public string user_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
